blog/urls.py
from django.urls import path
from . import views

app_name='blog'

urlpatterns = [
	path('', views.all_blogs, name='all_blogs'),
	path('<int:blog_id>/', views.detail, name='detail'),
]

personal_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from portfolio import views


 
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('blog/', include('blog.urls')),
    path('portfolio/', include('portfolio.urls')),
    path('', views.index, name='index'),
    path('video/', views.index, name='index'),
 ]	


urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portfolio/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('', views.index, name='index'),


]

video/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),

]

blog/models.py
from django.db import models

class 	Blog(models.Model):
	title=models.TextField(max_length=200)
	description=models.TextField()
	date=models.DateField()
	

portfolio/models.py
from django.db import models
from ckeditor.fields import RichTextField

class	Heading(models.Model):
    	content = RichTextField()

class 	Project(models.Model):
	title=models.CharField(max_length=100)
	description=RichTextField()
	image=models.ImageField(upload_to='portfolio/images/')
	realeseddate=models.DateField()
	url=models.URLField(blank=True);

class 	Video(models.Model):
	caption=models.CharField(max_length=300)
	video= models.FileField(upload_to='video/')	
	def _str_(self):
		return self.caption

video/models.py
from django.db import models

class Video(models.Model):
	caption=models.CharField(max_length=300)
	video= models.FileField(upload_to="video/%y")	
	def _str_(self):
		return self.caption

blog/views.py
from django.shortcuts import render,get_object_or_404
from .models import Blog

def all_blogs(request):
	blogs=Blog.objects.order_by('date')[:5]
	return render(request, 'blog/all_blogs.html',{'blogs':blogs})

def detail(request, blog_id):
	blog = get_object_or_404(Blog, pk=blog_id)
	return render(request, 'blog/detail.html',{'blog':blog})

portfolio/views.py
from django.shortcuts import render
from .models import Project
from .models import Video

def home(request):
	projects=Project.objects.all()
	return render(request,'portfolio/home.html',{'projects':projects})
def index(request):
	videos=Video.objects.all()	
	return render(request, 'portfolio/home.html', {'videos':videos})

video/views.py
from django.shortcuts import render
from .models import Video


def index(request):
	video=Video.objects.all()	
	return render(request, "index.html", {"video":video})

blog/templates/blog/all_blogs.html
{% extends 'portfolio/base.html' %}
{% block content %}


<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossorigin="anonymous">

Hello in my blog

{% for blog in blogs %}

<a 	href="{% url 'blog:detail' blog.id %}"><h2>{{ blog.title }}</h2></a>
<h5>{{ blog.date }}</h5>
<p>{{ blog.description|striptags|truncatechars:100 }} </p>


{% endfor %}

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-p34f1UUtsS3wqzfto5wAAmdvj+osOnFyQFpp4Ua3gs/ZVWx6oOypYoCJhGGScy+8" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.min.js" integrity="sha384-lpyLfhYuitXl2zRZ5Bn2fqnhNAKOAaM/0Kr9laMspuaMiZfGmfwRNFh8HlMy49eQ" crossorigin="anonymous"></script>
    -->
  </body>
</html>

{% endblock %}

blog/templates/blog/detail.html
{% extends 'portfolio/base.html' %}
{% block content %}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossorigin="anonymous">

{{ blog.title }}
<br>
{{ blog.description|safe }}
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-p34f1UUtsS3wqzfto5wAAmdvj+osOnFyQFpp4Ua3gs/ZVWx6oOypYoCJhGGScy+8" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.min.js" integrity="sha384-lpyLfhYuitXl2zRZ5Bn2fqnhNAKOAaM/0Kr9laMspuaMiZfGmfwRNFh8HlMy49eQ" crossorigin="anonymous"></script>
    -->
  </body>
</html>

{% endblock %}

portfolio/templates/portfolio/base.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossorigin="anonymous">
	  <link href="https://fonts.googleapis.com/css2?family=Zeyada&display=swap" rel="stylesheet">
	  <link href="https://fonts.googleapis.com/css2?family=Dawning+of+a+New+Day&display=swap" rel="stylesheet">

 <!-- social media button  -->
 <meta name="viewport" content="width=device-width, initial-scale=1">
 <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">


<body>  
<style>
.navbar {
  background-color: transparent !important;
}

<1--font-family:'Dawning of a New Day', cursive;->

html {
  height: 100%;
}

body {
  background: #000;
  position: relative;
  height: 100%;
}

.arrow-container {
  display: block;
  width: 200px;
  height: 100px;
  bottom: 100px;
  position: relative;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%) rotateZ(0deg);
}
.arrow-container:hover {
  cursor: pointer;
}
.arrow-container:hover .arrow {
  top: 50%;
}
.arrow-container:hover .arrow:before {
  transform: translate(-50%, -50%) rotateZ(-30deg);
}
.arrow-container:hover .arrow:after {
  transform: translate(-50%, -50%) rotateZ(30deg);
}

.arrow {
  position: absolute;
  left: 50%;
  transition: all 0.4s ease;
}
.arrow:before, .arrow:after {
  transition: all 0.4s ease;
  content: "";
  display: block;
  position: absolute;
  transform-origin: bottom right;
  background: rgb(204, 30, 30);
  width: 2px;
  height: 15px;
  border-radius: 1px;
  transform: translate(-50%, -50%) rotateZ(-45deg);
}
.arrow:after {
  transform-origin: bottom left;
  transform: translate(-50%, -50%) rotateZ(45deg);
}
.arrow:nth-child(1) {
  opacity: 0.3;
  top: 35%;
}
.arrow:nth-child(2) {
  opacity: 0.6;
  top: 55%;
}
.arrow:nth-child(3) {
  opacity: 0.9;
  top: 75%;
}

.scrollable{
  overflow-y: auto;
  max-height: 180px;
  width: 945px;
}

@import url(https://fonts.googleapis.com/css?family=Josefin+Sans:300,400);
* {
  margin: 0;
  padding: 0;
}
html, body {
  height: 100%;
}
section {
  position: relative;
  width: 100%;
  height: 100%;
}
section::after {
  position: absolute;
  bottom: 0%;
  left: 0;
  content: '';
  width: 100%;
  height: 80%;
  background: -webkit-linear-gradient(top,rgba(0,0,0,0) 0,rgba(0,0,0,.8) 80%,rgba(0,0,0,.8) 100%);
  background: linear-gradient(to bottom,rgba(0,0,0,0) 0,rgba(0,0,0,.8) 80%,rgba(0,0,0,.8) 100%);
}
section h1 {
  position: absolute;
  top: 50%;
  left: 50%;
  z-index: 2;
  -webkit-transform: translate(-50%, -50%);
  transform: translate(-50%, -50%);
  color: #fff;
  font : normal 300 64px/1 'Josefin Sans', sans-serif;
  text-align: center;
  white-space: nowrap;
}

#section01 { background: url(https://www.nxworld.net/example/css-scroll-down-button/bg01.jpg) center center / cover no-repeat;}
#section02 { background: url(https://www.nxworld.net/example/css-scroll-down-button/bg02.jpg) center center / cover no-repeat;}
#section03 { background: url(https://www.nxworld.net/example/css-scroll-down-button/bg03.jpg) center center / cover no-repeat;}
#section04 { background: url(https://www.nxworld.net/example/css-scroll-down-button/bg04.jpg) center center / cover no-repeat;}
#section05 { background: url(https://www.nxworld.net/example/css-scroll-down-button/bg05.jpg) center center / cover no-repeat;}
#section06 { background: url(https://www.nxworld.net/example/css-scroll-down-button/bg06.jpg) center center / cover no-repeat;}
#section07 { background: url(https://www.nxworld.net/example/css-scroll-down-button/bg07.jpg) center center / cover no-repeat;}
#section08 { background: url(https://www.nxworld.net/example/css-scroll-down-button/bg08.jpg) center center / cover no-repeat;}
#section09 { background: url(https://www.nxworld.net/example/css-scroll-down-button/bg09.jpg) center center / cover no-repeat;}
#section10 { background: url(https://www.nxworld.net/example/css-scroll-down-button/bg10.jpg) center center / cover no-repeat;}

#thanks {
  background-color: #fff;
}
#thanks::after {
  content: none;
}
#thanks div {
  position: absolute;
  top: 50%;
  left: 50%;
  z-index: 2;
  -webkit-transform: translate(-50%, -50%);
  transform: translate(-50%, -50%);
  text-align: center;
}
#thanks h2 {
  margin-bottom: 60px;
  color: #333;
  font : normal 300 64px/1 'Josefin Sans', sans-serif;
  text-align: center;
  white-space: nowrap;
}
#thanks p {
  color: #333;
  font : normal 400 20px/1 'Josefin Sans', sans-serif;
}
#thanks p a {
  color: #333;
  text-decoration: none;
  transition: color .3s;
}
#thanks p a:hover {
  color: #888;
}
.demo a {
  position: absolute;
  bottom: 100px;
  left: 50%;
  z-index: 2;
  display: inline-block;
  -webkit-transform: translate(0, -50%);
  transform: translate(0, -50%);
  color: #fff;
  font : normal 400 20px/1 'Josefin Sans', sans-serif;
  letter-spacing: .1em;
  text-decoration: none;
  transition: opacity .3s;
}
.demo a:hover {
  opacity: .5;
}

#section03 a {
  padding-top: 60px;
}
#section03 a span {
  position: absolute;
  top: 0;
  left: 50%;
  width: 46px;
  height: 46px;
  margin-left: -23px;
  border: 1px solid #fff;
  border-radius: 100%;
  box-sizing: border-box;
}
#section03 a span::after {
  position: absolute;
  top: 50%;
  left: 50%;
  content: '';
  width: 16px;
  height: 16px;
  margin: -12px 0 0 -8px;
  border-left: 1px solid #fff;
  border-bottom: 1px solid #fff;
  -webkit-transform: rotate(-45deg);
  transform: rotate(-45deg);
  box-sizing: border-box;
}
#section03 a span::before {
  position: absolute;
  top: 0;
  left: 0;
  z-index: -1;
  content: '';
  width: 44px;
  height: 44px;
  box-shadow: 0 0 0 0 rgba(255,255,255,.1);
  border-radius: 100%;
  opacity: 0;
  -webkit-animation: sdb03 3s infinite;
  animation: sdb03 3s infinite;
  box-sizing: border-box;
}
@-webkit-keyframes sdb03 {
  0% {
    opacity: 0;
  }
  30% {
    opacity: 1;
  }
  60% {
    box-shadow: 0 0 0 60px rgba(255,255,255,.1);
    opacity: 0;
  }
  100% {
    opacity: 0;
  }
}
@keyframes sdb03 {
  0% {
    opacity: 0;
  }
  30% {
    opacity: 1;
  }
  60% {
    box-shadow: 0 0 0 60px rgba(255,255,255,.1);
    opacity: 0;
  }
  100% {
    opacity: 0;
  }
}

.carousel-control-prev-icon, .carousel-control-next-icon {
    height: 30px;
    width: 30px;
    outline: black;
    background-color: rgba(14, 11, 11, 0.603);
    background-size: 110%, 110%;
    border-radius: 50%;
    border: 1px solid black;
}

.social-buttons {
  display: flex;
  align-items: center; /* flex vertical alignment */
  justify-content: space-evenly; /* flex horiz alignment - center is better */
  }

.social-margin{
  }

.social-icon {
  box-sizing: border-box;
  border-radius: 138px;
  border: 5px solid;
  text-align: center;
  width: 30px;
  height: 30px;
  line-height: 1px;
  transition: all 0.5s;
}

.social-icon-no-border {
 box-sizing: border-box;
  border-radius: 150px;
  text-align: center;
  width: 30px;
  height: 30px;
  transition: all 0.5s;
}

.social-icon:hover {
  transform: rotate(360deg)scale(1.3);
}

.social-icon-no-border:hover {
  transform: rotate(360deg)scale(1.3);
}


/* Facebook Button Styling */

.facebook {
  font-size: 15px;
  padding-top: 3px;
  border-color: #3b5998;
  background-color: #3b5998;
  color: #ffffff;
}

.twitter {
  font-size: 15px;
  padding-top: 10px;
  padding-left: 2px;
  border-color: #55acee;
  background-color: #55acee;
  color: #ffffff;
}


.youtube {
  font-size: 20px;
  padding-top: 0px;
  padding-left: 0px;
  background-color: #bb0000;
  color: #ffffff;
  border-color: #bb0000;
}

.instagram {
  font-size:  20px;
  padding-top: px;
  padding-bottom: 2px;
  background: -webkit-radial-gradient(circle at 30% 107%, #fdf497 0%, #fdf497 5%, #fd5949 45%, #d6249f 60%, #285AEB 90%);
  background: radial-gradient(circle at 30% 107%, #fdf497 0%, #fdf497 5%, #fd5949 45%, #d6249f 60%, #285AEB 90%);
  color: #ffffff;
}

.soundcloud {
  font-size: 15px;
  padding-top: 4px;
  padding-left: 0px;
  background-color: #e95d0c;
  color: #ffffff;
  border-color: #e95d0c;
}
.amazon {
  font-size: 20px;
  padding-top: 2px;
  padding-left: 0px;
  background-color: #050797;
  color: #ffffff;
  border-color: #050797;
}
.spotify {
  font-size: 22px;
  padding-top: px;
  padding-left: 0px;
  background-color: #1f9415;
  color: #000000;
  border-color: #1f9415;
}
.apple {
  font-size: 20px;
  padding-top: 0px;
  padding-left: 0px;
  background-color: #414241;
  color: #000000;
  border-color: #414241; 
}

.phone {
  font-size: 20px;
  padding-top: 0px;
  padding-left: 0px;
  background-color: #000000;
  color: #ffffff;
  border-color: #000000;
}

.bio {  
  box-sizing: border-box;
  border-radius: 138px;
  text-align:left ;
  width: 30px;
  height: 30px;
  line-height: 0px;
  transition: all 0.5s;
  font-size: 20px;  
  padding-top: 0px;
  background-color: #ff0101;
  color: #000000;
  border-color: #ff0101;
}
</style>
</head>
<body>
{% load static %}

<nav class="navbar fixed-top navbar-light bg-light">
  <div class="container-fluid">
    <div class="row">
      <a class="navbar-brand" href="{% url 'home' %}" style="font-family: 'Zeyada', cursive;color:#D7D7D7;font-size:3vw" font-size:40px>&nbsp josef lynn</a>
   <!-- <button class="btn" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation" style="color:#D7D7D7" >
    <span class="navbar-toggler-icon"></span>
    </button>-->
    </div>
    <form class="form-inline my-2 my-lg-0"></form>
      <div class="social-buttons">
        <a href="https://www.facebook.com/joseflynnmusic" target="blank" class="social-margin">
          <div class="social-icon facebook">
            <i class="fa fa-facebook" aria-hidden="true"></i>
          </div>
        </a>&nbsp
        <a href="https://www.instagram.com/josef.lynn/" target="blank" class="social-margin">
          <div class="social-icon-no-border instagram">
            <i class="fa fa-instagram" aria-hidden="true"></i>
          </div>
        </a>&nbsp
        <a href="https://www.youtube.com/channel/UCpk9-AAChhfOtWZDA5z8NrQ" target="blank" class="social-margin">
          <div class="social-icon youtube">
            <i class="fa fa-youtube" aria-hidden="true"></i>
          </div>
        </a>&nbsp
        <a href="https://soundcloud.com/user-422773367" target="blank" class="social-margin">
          <div class="social-icon soundcloud">
            <i class="fa fa-soundcloud" aria-hidden="true"></i>
          </div>
        </a>&nbsp
        <a href="https://open.spotify.com/artist/3nazeoh2QbBv6NOdWRBoI0?si=jbhpU_QiRiOI8ChWMm8u-Q" target="blank" class="social-margin">
          <div class="social-icon spotify">
            <i class="fa fa-spotify" aria-hidden="true"></i>
          </div>
        </a>&nbsp
        <a href="https://www.facebook.com/joseflynnmusic" target="blank" class="social-margin">
          <div class="social-icon amazon">
            <i class="fa fa-amazon" aria-hidden="true"></i>
          </div>
        </a>&nbsp
        <a href="https://www.facebook.com/joseflynnmusic" target="blank" class="social-margin">
          <div class="social-icon apple">
            <i class="fa fa-apple" aria-hidden="true"></i>
          </div>
        </a>&nbsp
          <a href="https://www.facebook.com/joseflynnmusic" target="blank" class="social-margin">
            <div class="social-icon phone">
              <i class="fa fa-phone" aria-hidden="true"></i>
            </div>
        </a>&nbsp 
          <a class="nav-link active" aria-current="page" href="http://127.0.0.1:8000/portfolio/#bio" style="color:#D7D7D7; font-size:15px"> #Bio</a> 
      <a class="nav-link active" aria-current="page" href="{% url 'blog:all_blogs' %}" style="cursive;color:#D7D7D7;font: size 15px">#SongsAreLikeTatoo</a>
    </div>

        <!---
        <li class="nav-item">
          <a class="nav-link" href="#" style="color:#D7D7D7">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false" style="color:#D7D7D7">
            Dropdown
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown" style="color:#D7D7D7">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true" style="color:#D7D7D7" >Disabled</a>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" >
        <button class="btn btn-outline-light" type="submit" style="color:#D7D7D7" >Search</button>
      </form> --->
    </div>
  </div>
</nav>


{% block content %}
{% endblock %}

portfolio/templates/portfolio/home.html
{% extends 'portfolio/base.html' %}
{% block content %}



<link href="https://fonts.googleapis.com/css2?family=Zeyada&display=swap" rel="stylesheet">

<!-- a href="{% url 'blog:all_blogs' %}">Blog</a>
{% load static %}
<!---<img src= "{% static 'portfolio/figo1.jpg' %}">


<link rel="icon" type="image/png" href="{% static 'portfolio/figo3.png' %">
<br>
<br>
<br>
<br>
<a href="{% static 'portfolio/figo.jpg' %}">Photo</a>
-->
<div class="card text-white bg-dark mb-3" >
  	<video  loop autoplay muted controls>
  	  	<source src="{% static 'portfolio/video1.mp4' type='video/mp4' %}">
  	Your browser does not support the video tag.
	<button id="unmuteButton"></button>unmuteButton.addEventListener('click', function() {video.muted = false;});
	</script>
	</video>
	<section id="section03" class="demo">
    <a href="#down"><div id="down"></div><span>
    </span>Scroll</a>
</section>
</div>
<!--ARRROw-->
<!--<html>
	<a href="#down" class="arrow-container">
  		<div class="arrow"></div>
  		<div class="arrow"></div>
  		<div class="arrow"></div>
	</a>
	<div id="down">
</html>
	-->

</div>
<div class="card text-white bg-dark mb-3">
  <h3 class="text-center mt-2 mb-2" </h3>
    <p class="card-text">Welcome to Josef Lynn official website</p>
    <!--<p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p> -->
	<a id="bio">
<a href="#" class="btn btn-primary">Go somewhere</a>
<a href="#" class="btn btn-primary">Go somewhere</a>
<a href="#" class="btn btn-primary">Go somewhere</a>
</div>

 <!--carousel-->

<!--<div class="card text-white bg-dark mb-3">	   -->
<div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
 	<div class="carousel-inner">
 		<div class="carousel-item active">
			{%for project in projects %}
 			<div class="card text-white bg-dark mb-3" style="max-width: 1500px;height:25rem;"> 	
            	<div class="row g-0">
            	  <div class="col-md-4">
            		<img src="{{ project.image.url }}" class="d-block w-100" height=400 width=400>
            	  </div>
            	 <div class="col-md-8">
            	    <div class="card-body">
            	      <h5 class="card-title">{{ project.title }}</h5>
            	        <div class="card">
						  <div class="card-body" style="width: 800px ;height: 14rem;">
						  <div class="scrollable">
						  	<p class="card-text"></p>{{ project.description|safe }}</p>
						  </div>
						  </div>
						</div>
            	      <div class="w-100">
            	      <p class="card-text"><small class="text-muted">Released on {{ project.realeseddate }} </small></p>
            	      <iframe src="{{ project.url }}" width="970" height="80" frameborder="0" allowtransparency="true" allow="encrypted-media"></iframe>
            	      </div>
					  </div>
            	    </div>

            	</div>
			</div>
		</div>
        <div class="carousel-item">
			{% endfor %}
		</div>
		</div>
	<button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
    		<span class="carousel-control-prev-icon" aria-hidden="true"></span>
    		<span class="visually-hidden">Previous</span>
  		</button>
	<button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
    		<span class="carousel-control-next-icon" aria-hidden="true"></span>
    		<span class="visually-hidden">Next</span>
  	</button>
</div>

<!--









	<button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev"></div>
    		<span class="carousel-control-prev-icon" aria-hidden="true"></span></div>
    		<span class="visually-hidden">Previous</span></div>
  		</button>
	<button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
    		<span class="carousel-control-next-icon" aria-hidden="true"></span>
    		<span class="visually-hidden">Next</span>
  		</button>
	</div>
</div>{%for project in projects %}
	<h1>{{ project.title }}<h1>
	<p>{{ project.description }}<p>
	<img src="{{ project.image.url }}" height=300 width=400>
	<br>
	{% if project.url %}
	<a href="{{ project.url }}">Link</a>
	{% endif %}

</body>
<script>'undefined'=== typeof _trfq || (window._trfq = []);'undefined'=== typeof _trfd && (window._trfd=[]),_trfd.push({'tccl.baseHost':'secureserver.net'}),_trfd.push({'ap':'cpsh'},{'server':'p3plcpnl0769'}) // Monitoring performance to make your website faster. If you want to opt-out, please contact web hosting support.</script><script src='https://img1.wsimg.com/tcc/tcc_l.combined.1.0.6.min.js'></script></html>

{% endfor %}
--->
<!--



    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-p34f1UUtsS3wqzfto5wAAmdvj+osOnFyQFpp4Ua3gs/ZVWx6oOypYoCJhGGScy+8" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.min.js" integrity="sha384-lpyLfhYuitXl2zRZ5Bn2fqnhNAKOAaM/0Kr9laMspuaMiZfGmfwRNFh8HlMy49eQ" crossorigin="anonymous"></script>
    -->
  </body>
</html>

{% endblock %}
`

video/templates/index.html
<h1> hello </h1>
<br>
<div class="container"
		{% for x in video %}
		<h3 class="text-center mt-2 mb-2">{{x.caption}}</h3>
		<video class="video-fluid" autoplay loop controls="controls">
			<source src="{{x.video.url}}" type="video/mp4" />
 	 	 </video>
 	 {% endfor %}